//! This library provides all data definitions for the Abstract Syntax Tree (AST)
//! for the Workflow Definition Language (WDL).
//!
//! The AST is generated by the parser and consumed by the interpreter and
//! probably by additional tooling in the future.

pub mod declaration;
pub use declaration::*;
pub mod expression;
pub use expression::*;
pub mod identifier;
pub use identifier::*;
pub mod location;
pub use location::*;
pub mod node;
pub use node::*;
pub mod span;
pub use span::*;
pub mod statement;
pub use statement::*;
pub mod workflow;
pub use workflow::*;
