[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
tonic = "0.11"
prost = "0.12"
serde = "1.0.197"
tokio = "1.37.0"

[build-dependencies]
tonic-build = "0.11"
