[package]
name = "wdl-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
router = { path = "../router" }
parser = { path = "../parser" }
interpreter = { path = "../interpreter", features = ["playground"] }

axum = "0.7.4"
shuttle-axum = "0.44.0"
shuttle-runtime = "0.44.0"
tokio = "1.28.2"
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["fs", "cors"] }
socketioxide = "0.13.0"
serde_json = "1.0.116"
