[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }

async-recursion = "1.0.5"
futures = "0.3.29"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
